# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Dominic Casillano 
description: Dominic Casillano's personal site!
baseurl: ""
# url: https://hacked-jekyll.netlify.app

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Dominic Casillano
  description:
    - Hello!
    - I like to build stuff.
    - Check out some of my projects below.
    - Feel free to reach out to me!
  cv: assets/cv.pdf
  address:
    - Toronto, Canada
#   - Department of Themes
#   - 123 Main St, Anytown, USA
  contact:
    email: dominiccasillano710@gmail.com
  profiles:
    linkedin: https://www.linkedin.com/in/dcasillano
    github: https://github.com/casillano

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
